-- Capstead owns these tables. Idempotent DDL applied at startup by CapsteadSchemaInitializer.
-- Portable across PostgreSQL 10+ and H2 (IF NOT EXISTS, VARCHAR-typed id + captured columns).

-- One row per capability execution (the governed business-capability call). Holds the lifecycle
-- fields, the principal it ran for, its parent (for the nested-capability execution tree), and
-- totals rolled up from this execution's model invocations for fast scorecard aggregation.
CREATE TABLE IF NOT EXISTS capstead_execution (
    execution_id         VARCHAR(64)  PRIMARY KEY,
    parent_execution_id  VARCHAR(64),
    capability_name      VARCHAR(255) NOT NULL,
    version              VARCHAR(64)  NOT NULL,
    domain               VARCHAR(255),
    principal            VARCHAR(255),
    started_at           TIMESTAMP    NOT NULL,
    finished_at          TIMESTAMP    NOT NULL,
    duration_ms          BIGINT       NOT NULL,
    success              BOOLEAN      NOT NULL,
    error_type           VARCHAR(255),
    retries              INTEGER      NOT NULL DEFAULT 0,
    model_invocations    INTEGER      NOT NULL DEFAULT 0,
    total_input_tokens   BIGINT       NOT NULL DEFAULT 0,
    total_output_tokens  BIGINT       NOT NULL DEFAULT 0,
    total_cost           NUMERIC(18, 6),
    captured_input       VARCHAR(8000),
    captured_output      VARCHAR(8000)
);

-- One row per model/LLM call made inside a capability execution. A single capability may call the
-- model several times (retries, multi-step, fan-out), each with its own model + token usage + cost;
-- this table is where that per-model breakdown lives, so cost can be attributed per model.
CREATE TABLE IF NOT EXISTS capstead_model_invocation (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id   VARCHAR(64)  NOT NULL REFERENCES capstead_execution (execution_id),
    seq            INTEGER      NOT NULL,
    model          VARCHAR(255),
    input_tokens   INTEGER      NOT NULL DEFAULT 0,
    output_tokens  INTEGER      NOT NULL DEFAULT 0,
    estimated_cost NUMERIC(18, 6),
    invoked_at     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_capstead_execution_coordinates ON capstead_execution (capability_name, version);
CREATE INDEX IF NOT EXISTS idx_capstead_execution_started_at ON capstead_execution (started_at);
CREATE INDEX IF NOT EXISTS idx_capstead_execution_parent ON capstead_execution (parent_execution_id);
CREATE INDEX IF NOT EXISTS idx_capstead_model_invocation_execution ON capstead_model_invocation (execution_id);
CREATE INDEX IF NOT EXISTS idx_capstead_model_invocation_model ON capstead_model_invocation (model);
