-- Capstead-owned tables — MySQL variant. Applied at startup by CapsteadSchemaInitializer when the
-- connected database is MySQL/MariaDB.
--
-- MySQL differences from the default (PostgreSQL/H2) script:
--   * no `GENERATED BY DEFAULT AS IDENTITY` -> use AUTO_INCREMENT
--   * no `CREATE INDEX IF NOT EXISTS` -> indexes are declared inline so `CREATE TABLE IF NOT EXISTS`
--     stays idempotent
--   * DATETIME(3) instead of TIMESTAMP (millisecond precision, no 2038 limit / auto-update behaviour)
--   * TEXT for captured input/output (avoids the InnoDB row-size limit)

CREATE TABLE IF NOT EXISTS capstead_execution (
    execution_id         VARCHAR(64)  NOT NULL,
    parent_execution_id  VARCHAR(64),
    capability_name      VARCHAR(255) NOT NULL,
    version              VARCHAR(64)  NOT NULL,
    domain               VARCHAR(255),
    principal            VARCHAR(255),
    started_at           DATETIME(3)  NOT NULL,
    finished_at          DATETIME(3),
    duration_ms          BIGINT       NOT NULL,
    success              BOOLEAN      NOT NULL,
    error_type           VARCHAR(255),
    retries              INT          NOT NULL DEFAULT 0,
    model_invocations    INT          NOT NULL DEFAULT 0,
    total_input_tokens   BIGINT       NOT NULL DEFAULT 0,
    total_output_tokens  BIGINT       NOT NULL DEFAULT 0,
    total_cost           DECIMAL(18, 6),
    captured_input       TEXT,
    captured_output      TEXT,
    PRIMARY KEY (execution_id),
    KEY idx_capstead_execution_coordinates (capability_name, version),
    KEY idx_capstead_execution_started_at (started_at),
    KEY idx_capstead_execution_parent (parent_execution_id)
);

CREATE TABLE IF NOT EXISTS capstead_model_invocation (
    id             BIGINT       NOT NULL AUTO_INCREMENT,
    execution_id   VARCHAR(64)  NOT NULL,
    seq            INT          NOT NULL,
    model          VARCHAR(255),
    input_tokens   INT          NOT NULL DEFAULT 0,
    output_tokens  INT          NOT NULL DEFAULT 0,
    estimated_cost DECIMAL(18, 6),
    invoked_at     DATETIME(3),
    PRIMARY KEY (id),
    KEY idx_capstead_model_invocation_execution (execution_id),
    KEY idx_capstead_model_invocation_model (model),
    CONSTRAINT fk_capstead_model_invocation_execution
        FOREIGN KEY (execution_id) REFERENCES capstead_execution (execution_id)
);
